package com.example.fitnesstrackingapp.data.model // Adjust package name as needed

import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.util.Date

/**
 * Represents a specific lift instance recorded by a user.
 *
 * @property id The unique ID of this lift entry (auto-generated by Firestore or set manually).
 * @property userId The ID of the user who performed this lift.
 * @property exerciseId The ID of the exercise performed (links to PredefinedExercises or an 'exercises' collection).
 * @property exerciseName The name of the exercise (denormalized for easier display).
 * @property date The date and time when the lift was performed.
 * @property weight The weight lifted (e.g., in kg or lbs).
 * @property reps The number of repetitions performed in a set.
 * @property sets The number of sets performed. (Note: This model assumes logging a summary of sets.
 *                 If logging individual sets, this model would change, or you'd have multiple UserLift entries.)
 * @property notes Optional notes about the lift (e.g., form, feeling).
 * @property isPr Boolean indicating if this lift was a personal record.
 * @property createdAt Timestamp when this lift record was created in Firestore.
 * @property unit The unit for weight (e.g., "kg", "lbs"). Can be user preference.
 */
data class UserLift(
    @DocumentId // Firestore will automatically populate this with the document ID
    var id: String? = null, // Made var to allow Firestore to set it after creation. Nullable until set.
    val userId: String = "",
    val exerciseId: String = "", // Corresponds to Exercise.id
    val exerciseName: String = "", // Denormalized for convenience
    @ServerTimestamp
    val date: Date? = null, // Date of the workout
    val weight: Double = 0.0,
    val reps: Int = 0,
    val sets: Int = 0, // Number of sets performed at this weight and rep count
    val notes: String? = null,
    val isPr: Boolean = false,
    val unit: String = "kg", // Default unit, can be user-configurable
    @ServerTimestamp
    val createdAt: Date? = null // Timestamp of when this record was created
) {
    // No-argument constructor for Firestore deserialization
    constructor() : this(null, "", "", "", null, 0.0, 0, 0, null, false, "kg", null)
}
