package com.example.fitnesstrackingapp.data.model // Adjust package name as needed

import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.util.Date

/**
 * Represents a user-created workout template.
 *
 * @property id The unique ID of this template (auto-generated by Firestore or set manually).
 * @property userId The ID of the user who created this template.
 * @property name The name of the workout template (e.g., "Push Day A", "Full Body Strength").
 * @property description Optional description of the template.
 * @property exercises A list of exercises included in this template.
 * @property createdAt Timestamp of when this template was created.
 * @property updatedAt Timestamp of when this template was last updated.
 * @property category Optional category for the template (e.g., "Strength", "Hypertrophy", "PPL").
 * @property daysScheduled List of days this template is typically scheduled for (e.g., ["Monday", "Thursday"]). (Conceptual)
 */
data class WorkoutTemplate(
    @DocumentId
    var id: String? = null, // Firestore document ID
    val userId: String = "",
    val name: String = "",
    val description: String? = null,
    val exercises: List<TemplateExercise> = emptyList(), // List of TemplateExercise objects
    @ServerTimestamp
    val createdAt: Date? = null,
    @ServerTimestamp
    val updatedAt: Date? = null,
    val category: String? = null
    // val daysScheduled: List<String> = emptyList() // Example for future scheduling features
) {
    // No-argument constructor for Firestore deserialization
    constructor() : this(null, "", "", null, emptyList(), null, null, null)
}
